/**
 * Catalog cases for the four standalone portals Sand Bench talks to as
 * external systems:
 *
 *   - gavriq-kafka-desk (Kafka portal — port 8095)
 *   - gavriq-mq-desk    (MQ portal    — port 8092)
 *   - gavriq-ftp-desk   (FTP portal   — port 18102 on staging)
 *   - gavriq-api-desk   (API portal   — port 8093)
 *
 * Each portal is deployed from its own repository with its own compose
 * project. The portals point at Sand Bench via SBE_STUB_BASE / SBE_APP_BASE
 * (host.docker.internal); the staging environment stores each portal URL in
 * its config.vars so the catalog's templating ({{kafkaPortal}}, {{mqPortal}},
 * {{ftpPortal}}, {{apiPortal}}) picks the right host per environment.
 *
 * Suites + type_keys surface as new submenu items under Quality assurance.
 */
import { CaseDef, SuiteDef, tagSource } from './types.ts';

const FILE = 'apps/api/src/catalog/sandbench-portal-cases.ts';

export const SANDBENCH_PORTAL_SUITES: SuiteDef[] = [
  {
    key: 'sb-kafka-portal',
    name: 'Kafka portal integration',
    description:
      'The standalone Kafka portal (gavriq-kafka-desk) answers its own health, reaches Sand Bench\'s testhub, and sends and receives messages through it.',
    typeKey: 'kafkaPortalIntegration',
    category: 'qa',
  },
  {
    key: 'sb-mq-portal',
    name: 'MQ portal integration',
    description:
      'The standalone MQ portal (gavriq-mq-desk) answers its own health, reaches Sand Bench\'s testhub, and exchanges messages through the testhub wire.',
    typeKey: 'mqPortalIntegration',
    category: 'qa',
  },
  {
    key: 'sb-ftp-portal',
    name: 'FTP portal integration',
    description:
      'The standalone FTP portal (gavriq-ftp-desk) answers its own health and lists the files that landed on the shared FTP volume.',
    typeKey: 'ftpPortalIntegration',
    category: 'qa',
  },
  {
    key: 'sb-api-portal',
    name: 'API portal integration',
    description:
      'The standalone API portal (gavriq-api-desk) answers its own health, reaches Sand Bench\'s API, and records inbound deliveries in its own ledger.',
    typeKey: 'apiPortalIntegration',
    category: 'qa',
  },
];

const C: CaseDef[] = [];

/* ------------------------------------------------------------------------- */
/* Kafka portal                                                              */
/* ------------------------------------------------------------------------- */

C.push(
  {
    key: 'SB-KAFKA-PORTAL-HEALTH',
    name: 'Kafka portal answers that it is healthy',
    objective: 'Confirm the Kafka portal is running and tells us so when asked, with its own service name.',
    description: 'GET {{kafkaPortal}}/health must return 200 with status "ok", service "kafkaportal" and decoupled true — proof the portal container is up and claims to be independent of Sand Bench\'s own API.',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'gavriq-kafka-desk compose project up; port 8095 reachable from the worker.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'status', equals: 'ok' }, { path: 'service', equals: 'kafkaportal' }, { path: 'decoupled', equals: true }],
        description: 'portal /health' },
    ],
    tags: ['integration', 'portal', 'kafka'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with service "kafkaportal" and decoupled true.',
  },
  {
    key: 'SB-KAFKA-PORTAL-READY',
    name: 'Kafka portal reports it is ready for traffic',
    objective: 'Confirm the Kafka portal says it is ready, which means its own state file and the wire it uses are in place.',
    description: 'GET {{kafkaPortal}}/ready returns 200 with ready true.',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'gavriq-kafka-desk portal container healthy.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/ready', expected_status: 200,
        expect_json: [{ path: 'ready', equals: true }], description: 'portal /ready' },
    ],
    tags: ['integration', 'portal', 'kafka'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 {"ready":true}.',
  },
  {
    key: 'SB-KAFKA-PORTAL-SBE-TESTHUB-REACHABLE',
    name: 'Kafka portal can reach the Sand Bench testhub',
    objective: 'Confirm the Kafka portal and Sand Bench\'s testhub can talk — a prerequisite for every send and receive.',
    description: 'GET {{kafkaPortal}}/app/status returns 200 and reports testhub.ok true against the testhub base it was configured with (host.docker.internal:18091 on staging).',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'Sand Bench testhub up on {{testhub}}; portal env SBE_STUB_BASE points at it.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/app/status', expected_status: 200,
        expect_json: [{ path: 'testhub.ok', equals: true }, { path: 'testhub.status', equals: 200 }],
        description: 'portal /app/status' },
    ],
    tags: ['integration', 'portal', 'kafka', 'connectivity'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with testhub.ok true.',
  },
  {
    key: 'SB-KAFKA-PORTAL-TOPIC-DEFAULT',
    name: 'Kafka portal advertises its default topic',
    objective: 'Confirm the portal reports the default Kafka topic it writes to, so cases can trust what topic their sends end up on.',
    description: 'GET {{kafkaPortal}}/health returns a non-empty topic field (default "sandbench.out").',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'Kafka portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'topic', exists: true }], description: 'portal /health' },
    ],
    tags: ['integration', 'portal', 'kafka', 'contract'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a topic field.',
  },
  {
    key: 'SB-KAFKA-PORTAL-HEADERS-CATALOG',
    name: 'Kafka portal publishes its header catalogue',
    objective: 'Confirm the portal returns the catalogue of headers it knows about, so test authors can see what every send is required to carry.',
    description: 'GET {{kafkaPortal}}/app/headers returns 200 and a non-empty data array that includes "x-sandbench-origin".',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'Kafka portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/app/headers', expected_status: 200,
        expect_json: [{ path: 'data', min_length: 1 }],
        expected_body_contains: 'x-sandbench-origin',
        description: 'portal /app/headers' },
    ],
    tags: ['integration', 'portal', 'kafka', 'catalog'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a non-empty header catalogue naming x-sandbench-origin.',
  },
  {
    key: 'SB-KAFKA-PORTAL-LOG-READABLE',
    name: 'Kafka portal activity log is readable',
    objective: 'Confirm the portal\'s recent-activity log is reachable even when nothing has happened yet — a baseline every send/receive case relies on.',
    description: 'GET {{kafkaPortal}}/app/log returns 200 with a data array (may be empty).',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'Kafka portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/app/log', expected_status: 200,
        expect_json: [{ path: 'data', exists: true }], description: 'portal /app/log' },
    ],
    tags: ['integration', 'portal', 'kafka', 'log'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a data array (empty or not).',
  },
  {
    key: 'SB-KAFKA-PORTAL-ROUND-TRIP',
    name: 'Kafka portal sends via testhub and the message comes back',
    objective: 'Confirm the end-to-end wire: when the portal sends a message, Sand Bench\'s testhub records it and the portal can read it back.',
    description: 'POST {{kafkaPortal}}/app/send {wire:"testhub",topic:"sandbench.out",key:"KAFKA-RT-{{random}}",payload:{...}} must be accepted (200/202). A second GET to /app/log then includes that key.',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'Portal up and testhub.ok true; portal pointed at staging testhub.',
    steps: [
      { action: 'request', method: 'POST', url: '{{kafkaPortal}}/app/send',
        body: { wire: 'testhub', topic: 'sandbench.out', key: 'KAFKA-RT', payload: { echo: 'KAFKA-RT-{{rand}}-{{ts}}' } },
        expected_status: [200, 202], description: 'portal /app/send via testhub' },
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'KAFKA-RT-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains the sent key' },
    ],
    tags: ['integration', 'portal', 'kafka', 'round-trip'],
    dataProfile: { profile: 'synthetic', data: 'A disposable Kafka record keyed with a per-run uuid.', source: 'generated at run time' },
    expected: 'Send accepted and the activity log contains the key.',
  },
  {
    key: 'SB-KAFKA-PORTAL-MULTI-SEND-INDEPENDENT',
    name: 'Kafka portal records two sequential sends as independent entries',
    objective: 'Confirm two sends in a row both land in the activity log, each keeping its own key — proof that one send does not clobber or shadow the next.',
    description: 'POST {{kafkaPortal}}/app/send twice with two distinct keys ("KAFKA-SEQ-A-{{rand}}" then "KAFKA-SEQ-B-{{rand}}"), then GET {{kafkaPortal}}/app/log once and expect the response to carry both keys.',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'Kafka portal up and testhub reachable; recent activity log readable.',
    steps: [
      { action: 'request', method: 'POST', url: '{{kafkaPortal}}/app/send',
        body: { wire: 'testhub', topic: 'sandbench.out', key: 'KAFKA-SEQ-A', payload: { echo: 'KAFKA-SEQ-A-{{rand}}-{{ts}}' } },
        expected_status: [200, 202], description: 'first send with key A' },
      { action: 'request', method: 'POST', url: '{{kafkaPortal}}/app/send',
        body: { wire: 'testhub', topic: 'sandbench.out', key: 'KAFKA-SEQ-B', payload: { echo: 'KAFKA-SEQ-B-{{rand}}-{{ts}}' } },
        expected_status: [200, 202], description: 'second send with key B' },
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'KAFKA-SEQ-A-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains first key' },
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'KAFKA-SEQ-B-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains second key' },
    ],
    tags: ['integration', 'portal', 'kafka', 'round-trip', 'multi-message'],
    dataProfile: { profile: 'synthetic', data: 'Two disposable Kafka records with distinct per-run keys.', source: 'generated at run time' },
    expected: 'Both sends accepted; the activity log contains both keys.',
  },
  {
    key: 'SB-KAFKA-PORTAL-INVALID-SEND-REJECTED',
    name: 'Kafka portal handles an empty send without a server error',
    objective: 'Confirm the portal does not crash on an empty send — the stub accepts it and records a row, but never returns a server error.',
    description: 'POST {{kafkaPortal}}/app/send with an empty body returns a 2xx or a 4xx, never a 5xx.',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'Kafka portal up.',
    steps: [
      { action: 'request', method: 'POST', url: '{{kafkaPortal}}/app/send', body: {},
        expected_status: [200, 202, 400, 422], description: 'empty POST handled cleanly, not 5xx' },
    ],
    tags: ['integration', 'portal', 'kafka', 'error-handling'],
    dataProfile: { profile: 'adversarial', data: 'An empty object; no topic, no payload.', source: 'inline' },
    expected: '2xx or 4xx; never 5xx.',
  },
  {
    key: 'SB-KAFKA-PORTAL-UI-SIGNATURE',
    name: 'Kafka portal landing page carries its own name',
    objective: 'Confirm a person browsing to the portal sees the Kafka desk, not a bare directory or someone else\'s page.',
    description: 'GET {{kafkaPortal}}/ returns 200 HTML whose body contains "Kafka".',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'Kafka portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/', expected_status: 200,
        expected_body_contains: 'Kafka', description: 'portal landing page' },
    ],
    tags: ['integration', 'portal', 'kafka', 'ui-signature'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 HTML containing "Kafka".',
  },
  {
    key: 'SB-KAFKA-PORTAL-DECOUPLED-FROM-SBE',
    name: 'Kafka portal keeps answering when Sand Bench\'s API is irrelevant to it',
    objective: 'Confirm the portal is architecturally independent: its own /health does not depend on the Sand Bench API being reachable.',
    description: 'GET {{kafkaPortal}}/health advertises decoupled true and never calls the Sand Bench API — the portal is its own service.',
    suiteKey: 'sb-kafka-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'Portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{kafkaPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'decoupled', equals: true }], description: 'portal reports decoupled true' },
    ],
    tags: ['integration', 'portal', 'kafka', 'architecture'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'decoupled true in /health.',
  },
);

/* ------------------------------------------------------------------------- */
/* MQ portal                                                                 */
/* ------------------------------------------------------------------------- */

C.push(
  {
    key: 'SB-MQ-PORTAL-HEALTH',
    name: 'MQ portal answers that it is healthy',
    objective: 'Confirm the MQ portal is up and names itself.',
    description: 'GET {{mqPortal}}/health must return 200 with status "ok", service "mqportal" and decoupled true.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'gavriq-mq-desk compose project up; port 8092 reachable from the worker.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'status', equals: 'ok' }, { path: 'service', equals: 'mqportal' }, { path: 'decoupled', equals: true }],
        description: 'portal /health' },
    ],
    tags: ['integration', 'portal', 'mq'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with service "mqportal".',
  },
  {
    key: 'SB-MQ-PORTAL-READY',
    name: 'MQ portal reports it is ready for traffic',
    objective: 'Confirm the MQ portal answers that it is ready to send and receive.',
    description: 'GET {{mqPortal}}/ready returns 200 {"ready":true}.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'MQ portal container healthy.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/ready', expected_status: 200,
        expect_json: [{ path: 'ready', equals: true }], description: 'portal /ready' },
    ],
    tags: ['integration', 'portal', 'mq'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 {"ready":true}.',
  },
  {
    key: 'SB-MQ-PORTAL-SBE-TESTHUB-REACHABLE',
    name: 'MQ portal can reach the Sand Bench testhub',
    objective: 'Confirm the MQ portal can talk to the testhub — the wire every send and receive goes through on staging.',
    description: 'GET {{mqPortal}}/app/status returns 200 and reports testhub.ok true against the testhub base it was configured with.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'Sand Bench testhub up on {{testhub}}; portal env SBE_STUB_BASE points at it.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/app/status', expected_status: 200,
        expect_json: [{ path: 'testhub.ok', equals: true }], description: 'portal /app/status' },
    ],
    tags: ['integration', 'portal', 'mq', 'connectivity'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'testhub.ok true in /app/status.',
  },
  {
    key: 'SB-MQ-PORTAL-HEADERS-CATALOG',
    name: 'MQ portal publishes its header catalogue',
    objective: 'Confirm the portal describes the headers every MQ message carries.',
    description: 'GET {{mqPortal}}/app/headers returns 200 with a non-empty data array including "x-sandbench-origin".',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'MQ portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/app/headers', expected_status: 200,
        expect_json: [{ path: 'data', min_length: 1 }],
        expected_body_contains: 'x-sandbench-origin',
        description: 'portal /app/headers' },
    ],
    tags: ['integration', 'portal', 'mq', 'catalog'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'Non-empty header catalogue naming x-sandbench-origin.',
  },
  {
    key: 'SB-MQ-PORTAL-LOG-READABLE',
    name: 'MQ portal activity log is readable',
    objective: 'Confirm the MQ portal returns its recent-activity list cleanly.',
    description: 'GET {{mqPortal}}/app/log returns 200 with a data array.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'MQ portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/app/log', expected_status: 200,
        expect_json: [{ path: 'data', exists: true }], description: 'portal /app/log' },
    ],
    tags: ['integration', 'portal', 'mq', 'log'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a data array.',
  },
  {
    key: 'SB-MQ-PORTAL-SEND-ACCEPTED',
    name: 'MQ portal accepts a well-formed send via testhub',
    objective: 'Confirm a well-formed send to the testhub wire is accepted and the activity log shows it afterward.',
    description: 'POST {{mqPortal}}/app/send {target:"testhub",queue:"DEV.QUEUE.1",payload:{...}} is accepted (200/202) and the log then contains the request id.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'MQ portal up; testhub reachable.',
    steps: [
      { action: 'request', method: 'POST', url: '{{mqPortal}}/app/send',
        body: { target: 'testhub', queue: 'DEV.QUEUE.1', payload: { echo: 'MQ-RT-{{rand}}-{{ts}}' } },
        expected_status: [200, 202], description: 'portal /app/send via testhub' },
      { action: 'request', method: 'GET', url: '{{mqPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'MQ-RT-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log reflects the send' },
    ],
    tags: ['integration', 'portal', 'mq', 'round-trip'],
    dataProfile: { profile: 'synthetic', data: 'A disposable MQ payload tagged with a per-run uuid.', source: 'generated at run time' },
    expected: 'Send accepted; log contains the per-run id.',
  },
  {
    key: 'SB-MQ-PORTAL-MULTI-SEND-INDEPENDENT',
    name: 'MQ portal records two sequential sends as independent entries',
    objective: 'Confirm two sends in a row both land in the activity log, each keeping its own tag — proof that one send does not clobber or shadow the next.',
    description: 'POST {{mqPortal}}/app/send twice with two distinct per-run tags, then GET {{mqPortal}}/app/log and expect the response to carry both tags.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'MQ portal up and testhub reachable; recent activity log readable.',
    steps: [
      { action: 'request', method: 'POST', url: '{{mqPortal}}/app/send',
        body: { target: 'testhub', queue: 'DEV.QUEUE.1', payload: { echo: 'MQ-SEQ-A-{{rand}}-{{ts}}' } },
        expected_status: [200, 202], description: 'first send with tag A' },
      { action: 'request', method: 'POST', url: '{{mqPortal}}/app/send',
        body: { target: 'testhub', queue: 'DEV.QUEUE.1', payload: { echo: 'MQ-SEQ-B-{{rand}}-{{ts}}' } },
        expected_status: [200, 202], description: 'second send with tag B' },
      { action: 'request', method: 'GET', url: '{{mqPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'MQ-SEQ-A-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains first tag' },
      { action: 'request', method: 'GET', url: '{{mqPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'MQ-SEQ-B-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains second tag' },
    ],
    tags: ['integration', 'portal', 'mq', 'round-trip', 'multi-message'],
    dataProfile: { profile: 'synthetic', data: 'Two disposable MQ payloads with distinct per-run tags.', source: 'generated at run time' },
    expected: 'Both sends accepted; the activity log contains both tags.',
  },
  {
    key: 'SB-MQ-PORTAL-INVALID-SEND-REJECTED',
    name: 'MQ portal handles an empty send without a server error',
    objective: 'Confirm the portal does not crash on an empty send — the stub accepts it and records a row, but never returns a server error.',
    description: 'POST {{mqPortal}}/app/send with an empty body returns a 2xx or a 4xx, never a 5xx.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'MQ portal up.',
    steps: [
      { action: 'request', method: 'POST', url: '{{mqPortal}}/app/send', body: {},
        expected_status: [200, 202, 400, 422], description: 'empty POST handled cleanly, not 5xx' },
    ],
    tags: ['integration', 'portal', 'mq', 'error-handling'],
    dataProfile: { profile: 'adversarial', data: 'An empty object.', source: 'inline' },
    expected: '2xx or 4xx; never 5xx.',
  },
  {
    key: 'SB-MQ-PORTAL-UI-SIGNATURE',
    name: 'MQ portal landing page carries its own name',
    objective: 'Confirm a person browsing to the portal sees the MQ desk.',
    description: 'GET {{mqPortal}}/ returns 200 HTML containing "MQ".',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'MQ portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/', expected_status: 200,
        expected_body_contains: 'MQ', description: 'portal landing page' },
    ],
    tags: ['integration', 'portal', 'mq', 'ui-signature'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 HTML containing "MQ".',
  },
  {
    key: 'SB-MQ-PORTAL-DECOUPLED-FROM-SBE',
    name: 'MQ portal keeps answering independently of Sand Bench',
    objective: 'Confirm the MQ portal is architecturally independent.',
    description: 'GET {{mqPortal}}/health reports decoupled true.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'MQ portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'decoupled', equals: true }], description: 'portal reports decoupled true' },
    ],
    tags: ['integration', 'portal', 'mq', 'architecture'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'decoupled true.',
  },
  {
    key: 'SB-MQ-PORTAL-UNKNOWN-ROUTE-404',
    name: 'MQ portal returns a clean 404 for unknown paths',
    objective: 'Confirm the portal returns a proper 404 rather than a 500 or an opaque hang when a path is wrong.',
    description: 'GET {{mqPortal}}/does/not/exist returns 404.',
    suiteKey: 'sb-mq-portal', testType: 'integration', method: 'http', severity: 'low', priority: 'p3',
    preconditions: 'MQ portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{mqPortal}}/does/not/exist', expected_status: 404,
        description: 'unknown path returns 404' },
    ],
    tags: ['integration', 'portal', 'mq', 'error-handling'],
    dataProfile: { profile: 'adversarial', data: 'A random unmapped path.', source: 'inline' },
    expected: '404 on unknown path.',
  },
);

/* ------------------------------------------------------------------------- */
/* FTP portal                                                                */
/* ------------------------------------------------------------------------- */

C.push(
  {
    key: 'SB-FTP-PORTAL-HEALTH',
    name: 'FTP portal answers that it is healthy',
    objective: 'Confirm the FTP portal is running and names itself.',
    description: 'GET {{ftpPortal}}/health returns 200 with status "ok", service "ftpdesk" and reports the FTP root it reads from.',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'gavriq-ftp-desk compose project up; port 18102 reachable from the worker.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'status', equals: 'ok' }, { path: 'service', equals: 'ftpdesk' }, { path: 'root', exists: true }],
        description: 'portal /health' },
    ],
    tags: ['integration', 'portal', 'ftp'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with service "ftpdesk".',
  },
  {
    key: 'SB-FTP-PORTAL-READY',
    name: 'FTP portal reports it is ready',
    objective: 'Confirm the FTP portal is ready for its reads.',
    description: 'GET {{ftpPortal}}/ready returns 200 {"ready":true}.',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'FTP portal container healthy.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/ready', expected_status: 200,
        expect_json: [{ path: 'ready', equals: true }], description: 'portal /ready' },
    ],
    tags: ['integration', 'portal', 'ftp'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 {"ready":true}.',
  },
  {
    key: 'SB-FTP-PORTAL-FILES-LIST',
    name: 'FTP portal lists the files on the shared volume',
    objective: 'Confirm the FTP portal returns a file listing — empty or not — rather than erroring on the shared FTP volume read.',
    description: 'GET {{ftpPortal}}/app/files returns 200 with a data array (possibly empty) representing files under the configured root.',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'FTP portal up; FTP data volume mounted read-only (may be empty on staging).',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/app/files', expected_status: 200,
        expect_json: [{ path: 'data', exists: true }], description: 'portal /app/files' },
    ],
    tags: ['integration', 'portal', 'ftp', 'files'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET; volume is mounted read-only.', source: 'n/a' },
    expected: '200 with a data array.',
  },
  {
    key: 'SB-FTP-PORTAL-FILES-PREFIX-FILTER-ACCEPTED',
    name: 'FTP portal accepts a prefix filter without error',
    objective: 'Confirm the files endpoint honours a prefix filter cleanly — important so test authors can scope the listing.',
    description: 'GET {{ftpPortal}}/app/files?prefix=none/nowhere/ returns 200 with a data array (expected empty for a bogus prefix).',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/app/files?prefix=none/nowhere/', expected_status: 200,
        expect_json: [{ path: 'data', exists: true }], description: 'portal /app/files?prefix=' },
    ],
    tags: ['integration', 'portal', 'ftp', 'filter'],
    dataProfile: { profile: 'none (read-only)', data: 'A prefix query string on a GET.', source: 'inline' },
    expected: '200 with a data array (empty for a bogus prefix).',
  },
  {
    key: 'SB-FTP-PORTAL-LOG-READABLE',
    name: 'FTP portal recent-arrivals log is readable',
    objective: 'Confirm the recent-arrivals view returns cleanly even with no deliveries yet.',
    description: 'GET {{ftpPortal}}/app/log returns 200 with a data array.',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/app/log', expected_status: 200,
        expect_json: [{ path: 'data', exists: true }], description: 'portal /app/log' },
    ],
    tags: ['integration', 'portal', 'ftp', 'log'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a data array.',
  },
  {
    key: 'SB-FTP-PORTAL-LEDGER-SEARCH',
    name: 'FTP portal ledger search answers cleanly with no match',
    objective: 'Confirm the ledger search endpoint answers 200 and returns no matches for a bogus query.',
    description: 'GET {{ftpPortal}}/app/ledger?q=NO-SUCH-NEEDLE returns 200 with a data array (empty expected).',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/app/ledger?q=NO-SUCH-NEEDLE', expected_status: 200,
        expect_json: [{ path: 'data', exists: true }], description: 'portal /app/ledger?q=' },
    ],
    tags: ['integration', 'portal', 'ftp', 'search'],
    dataProfile: { profile: 'synthetic', data: 'A deliberately missing search string.', source: 'inline' },
    expected: '200 with no matches.',
  },
  {
    key: 'SB-FTP-PORTAL-FILE-OUT-OF-ROOT-REFUSED',
    name: 'FTP portal refuses a path that escapes the FTP root',
    objective: 'Confirm the portal rejects a path that tries to climb out of the FTP root — the first path-traversal guard.',
    description: 'GET {{ftpPortal}}/app/file?name=../etc/passwd returns a 4xx (400).',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/app/file?name=../etc/passwd',
        expected_status: [400, 403], description: 'escape attempt rejected' },
    ],
    tags: ['integration', 'portal', 'ftp', 'security'],
    dataProfile: { profile: 'adversarial', data: 'A path with a parent-directory component.', source: 'inline' },
    expected: '400 or 403 refusing the escape, with a readable reason.',
  },
  {
    key: 'SB-FTP-PORTAL-FILE-NOT-FOUND-CLEAN-404',
    name: 'FTP portal returns a clean 404 for a missing file name',
    objective: 'Confirm the file-fetch endpoint tells us the file is missing — a plain 404 — rather than 500, hang, or an empty 200.',
    description: 'GET {{ftpPortal}}/app/file?name=no-such-file-{{rand}}.txt returns a 4xx (404 expected) with a readable reason.',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'FTP portal up; FTP root mounted; the generated name is unlikely to exist on the shared volume.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/app/file?name=no-such-file-{{rand}}.txt',
        expected_status: [404, 400], description: 'missing file returns a clean 404' },
    ],
    tags: ['integration', 'portal', 'ftp', 'files', 'error-handling'],
    dataProfile: { profile: 'synthetic', data: 'A randomised file name that will not exist on the FTP volume.', source: 'generated at run time' },
    expected: '404 (or 400) with a readable reason; never 5xx.',
  },
  {
    key: 'SB-FTP-PORTAL-UI-SIGNATURE',
    name: 'FTP portal landing page carries its own name',
    objective: 'Confirm the portal\'s page shows it is the FTP desk.',
    description: 'GET {{ftpPortal}}/ returns 200 HTML containing "FTP".',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/', expected_status: 200,
        expected_body_contains: 'FTP', description: 'portal landing page' },
    ],
    tags: ['integration', 'portal', 'ftp', 'ui-signature'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 HTML containing "FTP".',
  },
  {
    key: 'SB-FTP-PORTAL-UNKNOWN-ROUTE-404',
    name: 'FTP portal returns a clean 404 for unknown paths',
    objective: 'Confirm the portal 404s cleanly on unmapped paths rather than crashing.',
    description: 'GET {{ftpPortal}}/does/not/exist returns 404.',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'low', priority: 'p3',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/does/not/exist', expected_status: 404,
        description: 'unknown path returns 404' },
    ],
    tags: ['integration', 'portal', 'ftp', 'error-handling'],
    dataProfile: { profile: 'adversarial', data: 'A random unmapped path.', source: 'inline' },
    expected: '404 on unknown path.',
  },
  {
    key: 'SB-FTP-PORTAL-ROOT-ADVERTISED',
    name: 'FTP portal advertises the FTP root it reads from',
    objective: 'Confirm the portal tells operators where it is reading from, so a wrong mount is obvious.',
    description: 'GET {{ftpPortal}}/health returns a non-empty root value (default "/ftp").',
    suiteKey: 'sb-ftp-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'FTP portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{ftpPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'root', exists: true }], description: 'portal /health root' },
    ],
    tags: ['integration', 'portal', 'ftp', 'contract'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a root string.',
  },
);

/* ------------------------------------------------------------------------- */
/* API portal                                                                */
/* ------------------------------------------------------------------------- */

C.push(
  {
    key: 'SB-API-PORTAL-HEALTH',
    name: 'API portal answers that it is healthy',
    objective: 'Confirm the standalone API portal is up and names itself.',
    description: 'GET {{apiPortal}}/health returns 200 with status "ok", service "apiportal" and the ledger mode (postgres or memory).',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'gavriq-api-desk compose project up; port 8093 reachable; its Postgres healthy.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'status', equals: 'ok' }, { path: 'service', equals: 'apiportal' }, { path: 'mode', exists: true }],
        description: 'portal /health' },
    ],
    tags: ['integration', 'portal', 'api'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with service "apiportal" and a mode field.',
  },
  {
    key: 'SB-API-PORTAL-READY',
    name: 'API portal reports it is ready',
    objective: 'Confirm the API portal considers its ledger reachable and is ready for traffic.',
    description: 'GET {{apiPortal}}/ready returns 200 with ready true and mode set.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'API portal container healthy; its database healthy.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/ready', expected_status: 200,
        expect_json: [{ path: 'ready', equals: true }, { path: 'mode', exists: true }],
        description: 'portal /ready' },
    ],
    tags: ['integration', 'portal', 'api'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with ready true.',
  },
  {
    key: 'SB-API-PORTAL-SBE-APP-REACHABLE',
    name: 'API portal can reach the Sand Bench application',
    objective: 'Confirm the API portal can call back into Sand Bench — a prerequisite for every downstream round-trip test.',
    description: 'GET {{apiPortal}}/app/status returns 200 and reports app.ok true against the Sand Bench API base it was configured with.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'Sand Bench API up on {{api}}; portal env SBE_APP_BASE points at it.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/status', expected_status: 200,
        expect_json: [{ path: 'app.ok', equals: true }], description: 'portal /app/status' },
    ],
    tags: ['integration', 'portal', 'api', 'connectivity'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'app.ok true in /app/status.',
  },
  {
    key: 'SB-API-PORTAL-HEADERS-CATALOG',
    name: 'API portal publishes its header catalogue',
    objective: 'Confirm the portal returns the headers every inbound call is expected to carry.',
    description: 'GET {{apiPortal}}/app/headers returns 200 with a non-empty data array including "x-sandbench-origin".',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'API portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/headers', expected_status: 200,
        expect_json: [{ path: 'data', min_length: 1 }],
        expected_body_contains: 'x-sandbench-origin',
        description: 'portal /app/headers' },
    ],
    tags: ['integration', 'portal', 'api', 'catalog'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'Non-empty header catalogue naming x-sandbench-origin.',
  },
  {
    key: 'SB-API-PORTAL-INBOUND-RECORD',
    name: 'API portal records an inbound call in its ledger',
    objective: 'Confirm the portal\'s inbound endpoint records what it receives — the core of the "downstream API" simulation.',
    description: 'POST {{apiPortal}}/inbound/pacs.008 with a tagged body is accepted (200/201/202). A subsequent GET to /app/log then contains the tag.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'critical', priority: 'p0',
    preconditions: 'API portal up; its ledger reachable.',
    steps: [
      { action: 'request', method: 'POST', url: '{{apiPortal}}/inbound/pacs.008',
        body: { tag: 'API-RT-{{rand}}-{{ts}}', payload: { msg: 'api-portal-inbound' } },
        expected_status: [200, 201, 202], description: 'portal /inbound/pacs.008' },
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'API-RT-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains the inbound tag' },
    ],
    tags: ['integration', 'portal', 'api', 'inbound', 'round-trip'],
    dataProfile: { profile: 'synthetic', data: 'A disposable inbound body tagged with a per-run uuid.', source: 'generated at run time' },
    expected: 'Inbound accepted; log contains the tag.',
  },
  {
    key: 'SB-API-PORTAL-HOOK-RECORDS',
    name: 'API portal /hook records a posted payload',
    objective: 'Confirm the generic hook endpoint accepts and records a payload like a webhook sink would.',
    description: 'POST {{apiPortal}}/hook with a tagged body returns 2xx. GET {{apiPortal}}/app/log then contains the tag.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'API portal up.',
    steps: [
      { action: 'request', method: 'POST', url: '{{apiPortal}}/hook',
        body: { kind: 'api-portal-hook', hooktag: 'HOOK-{{rand}}-{{ts}}' },
        expected_status: [200, 201, 202], description: 'portal /hook' },
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/log', expected_status: 200,
        expected_body_contains: 'HOOK-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains the hook tag' },
    ],
    tags: ['integration', 'portal', 'api', 'hook'],
    dataProfile: { profile: 'synthetic', data: 'A tagged payload for the hook sink.', source: 'generated at run time' },
    expected: 'Hook accepted; log reflects it.',
  },
  {
    key: 'SB-API-PORTAL-EXPORT-JSON',
    name: 'API portal exports its ledger as JSON',
    objective: 'Confirm the portal can hand over its ledger as a JSON download, which operators use to audit a run.',
    description: 'GET {{apiPortal}}/app/export returns 200 with a JSON content type and a parseable payload.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'API portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/export', expected_status: 200,
        expect_headers: [{ name: 'content-type', contains: 'application/json' }],
        description: 'portal /app/export' },
    ],
    tags: ['integration', 'portal', 'api', 'export'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 with a JSON content type.',
  },
  {
    key: 'SB-API-PORTAL-EXPORT-REFLECTS-INBOUND',
    name: 'API portal export contains an inbound record posted moments earlier',
    objective: 'Confirm the ledger export is a true record of what the portal received — an inbound call with a unique tag is visible in the export seconds later.',
    description: 'POST {{apiPortal}}/inbound/pacs.008 with a per-run tag is accepted (200/201/202). GET {{apiPortal}}/app/export then returns 200 with a JSON body whose text contains that tag.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'API portal up; its ledger reachable; export endpoint enabled.',
    steps: [
      { action: 'request', method: 'POST', url: '{{apiPortal}}/inbound/pacs.008',
        body: { tag: 'API-EXP-{{rand}}-{{ts}}', payload: { msg: 'api-portal-export-reflects' } },
        expected_status: [200, 201, 202], description: 'inbound call tagged for later lookup' },
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/export', expected_status: 200,
        expect_headers: [{ name: 'content-type', contains: 'application/json' }],
        expected_body_contains: 'API-EXP-{{rand}}-{{ts}}',
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'export JSON contains the tag' },
    ],
    tags: ['integration', 'portal', 'api', 'export', 'round-trip'],
    dataProfile: { profile: 'synthetic', data: 'A disposable inbound body tagged with a per-run uuid.', source: 'generated at run time' },
    expected: 'Inbound accepted; the ledger export carries the tag.',
  },
  {
    key: 'SB-API-PORTAL-UI-SIGNATURE',
    name: 'API portal landing page carries its own name',
    objective: 'Confirm the portal\'s page shows it is the API desk.',
    description: 'GET {{apiPortal}}/ returns 200 HTML whose body contains "API".',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'API portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/', expected_status: 200,
        expected_body_contains: 'API', description: 'portal landing page' },
    ],
    tags: ['integration', 'portal', 'api', 'ui-signature'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: '200 HTML containing "API".',
  },
  {
    key: 'SB-API-PORTAL-DECOUPLED-FROM-SBE',
    name: 'API portal keeps answering independently of Sand Bench',
    objective: 'Confirm the API portal is its own service: /health does not fail if the Sand Bench API is unreachable.',
    description: 'GET {{apiPortal}}/health reports decoupled true.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'medium', priority: 'p2',
    preconditions: 'API portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/health', expected_status: 200,
        expect_json: [{ path: 'decoupled', equals: true }], description: 'portal reports decoupled true' },
    ],
    tags: ['integration', 'portal', 'api', 'architecture'],
    dataProfile: { profile: 'none (read-only)', data: 'A single GET.', source: 'n/a' },
    expected: 'decoupled true.',
  },
  {
    key: 'SB-API-PORTAL-UNKNOWN-ROUTE-404',
    name: 'API portal returns a clean 404 for unknown paths',
    objective: 'Confirm the portal does not crash or 500 on unmapped paths.',
    description: 'GET {{apiPortal}}/does/not/exist returns 404.',
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'low', priority: 'p3',
    preconditions: 'API portal up.',
    steps: [
      { action: 'request', method: 'GET', url: '{{apiPortal}}/does/not/exist', expected_status: 404,
        description: 'unknown path returns 404' },
    ],
    tags: ['integration', 'portal', 'api', 'error-handling'],
    dataProfile: { profile: 'adversarial', data: 'A random unmapped path.', source: 'inline' },
    expected: '404 on unknown path.',
  },
);

/* ------------------------------------------------------------------------- */
/* API portal — ISO consumer coverage                                        */
/* ------------------------------------------------------------------------- */

const ISO_TYPES: { code: string; title: string }[] = [
  { code: 'pacs.008.001.14', title: 'Customer Credit Transfer (v14)' },
  { code: 'pacs.008.001.08', title: 'FI to FI Customer Credit Transfer (v8)' },
  { code: 'pain.001.001.09', title: 'Customer Credit Transfer Initiation' },
  { code: 'pain.002.001.10', title: 'Customer Payment Status Report' },
  { code: 'camt.053.001.08', title: 'Bank to Customer Statement' },
];

for (const t of ISO_TYPES) {
  const safeKey = 'SB-API-PORTAL-INBOUND-' + t.code.replace(/\./g, '-').toUpperCase();
  C.push({
    key: safeKey,
    name: `API portal consumes a ${t.code} inbound call`,
    objective: `Confirm the standalone API portal records a ${t.title} (${t.code}) message when it arrives on its generic /inbound/{code} endpoint.`,
    description: `POST {{apiPortal}}/inbound/${t.code} with a per-run tag; GET {{apiPortal}}/app/log carries that tag within a short poll window.`,
    suiteKey: 'sb-api-portal', testType: 'integration', method: 'http', severity: 'high', priority: 'p1',
    preconditions: 'API portal up; ledger reachable.',
    steps: [
      { action: 'request', method: 'POST', url: `{{apiPortal}}/inbound/${t.code}`,
        body: { tag: `API-ISO-${t.code.toUpperCase().replace(/\./g, '-')}-{{rand}}-{{ts}}`, messageTypeCode: t.code, payload: { msg: `api-portal-${t.code}` } },
        expected_status: [200, 201, 202], description: `portal /inbound/${t.code}` },
      { action: 'request', method: 'GET', url: '{{apiPortal}}/app/log', expected_status: 200,
        expected_body_contains: `API-ISO-${t.code.toUpperCase().replace(/\./g, '-')}-{{rand}}-{{ts}}`,
        poll: { timeout_ms: 5000, interval_ms: 500 },
        description: 'log contains the per-run tag' },
    ],
    tags: ['integration', 'portal', 'api', 'iso', t.code],
    dataProfile: { profile: 'synthetic', data: `A disposable inbound body tagged with the ${t.code} code.`, source: 'generated at run time' },
    expected: `Inbound accepted; log reflects the tag for ${t.code}.`,
  });
}

export const SANDBENCH_PORTAL_CASES: CaseDef[] = tagSource(FILE, C);
