#!/usr/bin/env node
/**
 * Deploy a pinned Sand Bench commit as the local STAGING stack and register it
 * with the Test Engine as the environment "sand-bench-staging".
 *
 *   node deploy/staging/deploy.mjs deploy [--ref main] [--no-seed] [--no-register]
 *   node deploy/staging/deploy.mjs status
 *   node deploy/staging/deploy.mjs seed
 *   node deploy/staging/deploy.mjs register
 *   node deploy/staging/deploy.mjs stop
 *   node deploy/staging/deploy.mjs down [--rmi] [--volumes]   containers (+ images, + data) removed; engine told it is down
 *
 * The source is exported with `git archive`, so staging runs exactly what is
 * committed at <ref> — never the uncommitted working tree the development
 * stack is built from. State (exported sources, generated secrets) lives in
 * STAGING_HOME, outside both repositories.
 *
 *   SANDBENCH_REPO   Sand Bench checkout          (default ../sand-bench-enterprise)
 *   STAGING_HOME     state directory              (default ../sand-bench-staging)
 *   TE_BASE          Test Engine control plane    (default http://127.0.0.1:8797)
 *   STAGING_*_PORT   host ports                   (default 18080/18787/18091/18090)
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const PROJECT = 'sand-bench-staging';
const ENV_KEY = 'sand-bench-staging';
const SERVICES = ['db', 'minio', 'api', 'worker', 'web', 'testhub', 'dbviewer'];
const KEEP_SOURCES = 2;

const repo = path.resolve(process.env.SANDBENCH_REPO || path.join(root, '../sand-bench-enterprise'));
const home = path.resolve(process.env.STAGING_HOME || path.join(root, '../sand-bench-staging'));
const engine = (process.env.TE_BASE || 'http://127.0.0.1:8797').replace(/\/$/, '');
const ports = {
  web: Number(process.env.STAGING_WEB_PORT) || 18080,
  api: Number(process.env.STAGING_API_PORT) || 18787,
  testhub: Number(process.env.STAGING_TESTHUB_PORT) || 18091,
  dbviewer: Number(process.env.STAGING_DBVIEWER_PORT) || 18090,
};
const secretsFile = path.join(home, 'staging.env');
const stateFile = path.join(home, 'deployed.json');

function run(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, { encoding: 'utf8', windowsHide: true, maxBuffer: 64 * 1024 * 1024, ...opts });
  if (res.error) throw res.error;
  if (res.status !== 0) {
    throw new Error(`${cmd} ${args.slice(0, 4).join(' ')} … exited ${res.status}\n${(res.stderr || res.stdout || '').trim().slice(-2000)}`);
  }
  return (res.stdout || '').trim();
}

function option(args, name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}

/** Secrets are generated once and kept: the pepper and AES key must survive redeploys. */
function ensureSecrets() {
  if (existsSync(secretsFile)) return;
  const secret = () => randomBytes(32).toString('hex');
  const s3 = secret();
  writeFileSync(
    secretsFile,
    [
      '# Generated by deploy/staging/deploy.mjs — staging only. Do not commit.',
      `JWT_SECRET=${secret()}`,
      `PASSWORD_PEPPER=${secret()}`,
      `AES_ENCRYPTION_KEY=${secret()}`,
      `MINIO_ROOT_PASSWORD=${s3}`,
      `S3_SECRET_KEY=${s3}`,
      '',
    ].join('\n'),
    { mode: 0o600 }
  );
  console.log(`[staging] generated secrets → ${secretsFile}`);
}

function exportSource(ref) {
  if (!existsSync(path.join(repo, '.git'))) throw new Error(`Sand Bench checkout not found at ${repo} (set SANDBENCH_REPO)`);
  const commit = run('git', ['-C', repo, 'rev-parse', '--verify', `${ref}^{commit}`]);
  const tag = commit.slice(0, 12);
  const sources = path.join(home, 'src');
  const dir = path.join(sources, tag);
  if (!existsSync(path.join(dir, 'docker-compose.yml'))) {
    rmSync(dir, { recursive: true, force: true });
    mkdirSync(dir, { recursive: true });
    // Relative names only: GNU tar reads "C:\…" as a remote host.
    run('git', ['-C', repo, '-c', 'core.autocrlf=false', 'archive', '--format=tar', '-o', path.join(sources, `${tag}.tar`), commit]);
    run('tar', ['-xf', `${tag}.tar`, '-C', tag], { cwd: sources });
    rmSync(path.join(sources, `${tag}.tar`), { force: true });
    console.log(`[staging] exported ${ref} (${tag}) → ${dir}`);
  }
  let version = '0.0.0';
  try {
    version = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8')).version || version;
  } catch { /* keep default */ }
  const subject = run('git', ['-C', repo, 'log', '-1', '--format=%s', commit]);
  return { ref, commit, tag, dir, version, subject };
}

function pruneSources(keepTag) {
  const sources = path.join(home, 'src');
  const dirs = readdirSync(sources)
    .filter((name) => name !== keepTag && statSync(path.join(sources, name)).isDirectory())
    .sort((a, b) => statSync(path.join(sources, b)).mtimeMs - statSync(path.join(sources, a)).mtimeMs);
  for (const name of dirs.slice(KEEP_SOURCES - 1)) rmSync(path.join(sources, name), { recursive: true, force: true });
}

function compose(src, args, { inherit = true } = {}) {
  const base = [
    'compose', '-p', PROJECT, '--project-directory', src.dir, '--env-file', secretsFile,
    '-f', path.join(src.dir, 'docker-compose.yml'), '-f', path.join(here, 'compose.override.yml'),
  ];
  const env = {
    ...process.env,
    SBE_STAGING_TAG: src.tag,
    SBE_STAGING_COMMIT: src.commit,
    SBE_STAGING_VERSION: `${src.version}-staging`,
    STAGING_WEB_PORT: String(ports.web),
    STAGING_API_PORT: String(ports.api),
    STAGING_TESTHUB_PORT: String(ports.testhub),
    STAGING_DBVIEWER_PORT: String(ports.dbviewer),
  };
  return run('docker', [...base, ...args], inherit ? { env, stdio: 'inherit' } : { env });
}

async function probe(name, url, check) {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
    const text = await res.text();
    const detail = check ? check(res, text) : res.ok ? '' : `HTTP ${res.status}`;
    return { name, url, ok: !detail, detail: detail || `HTTP ${res.status}` };
  } catch (err) {
    return { name, url, ok: false, detail: err.cause?.code || err.message };
  }
}

async function verify() {
  const host = 'http://127.0.0.1';
  const checks = [
    await probe('api', `${host}:${ports.api}/health`, (res, text) => {
      if (!res.ok) return `HTTP ${res.status}`;
      const body = JSON.parse(text);
      return body.classification === 'test' ? '' : `classification is "${body.classification}", expected "test"`;
    }),
    await probe('web', `${host}:${ports.web}/index.html`),
    await probe('testhub', `${host}:${ports.testhub}/health`),
    await probe('dbviewer', `${host}:${ports.dbviewer}/health`),
  ];
  try {
    const res = await fetch(`${host}:${ports.api}/api/v1/session/login`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ tenantSlug: 'acme-demo', username: 'operator.acme' }),
      signal: AbortSignal.timeout(10_000),
    });
    const body = await res.json().catch(() => ({}));
    checks.push({ name: 'demo sign-in', url: `${host}:${ports.api}/api/v1/session/login`, ok: res.ok && !!body.token, detail: `HTTP ${res.status}` });
  } catch (err) {
    checks.push({ name: 'demo sign-in', url: '', ok: false, detail: err.cause?.code || err.message });
  }
  for (const c of checks) console.log(`[staging] ${c.ok ? 'ok  ' : 'FAIL'} ${c.name.padEnd(13)} ${c.detail}  ${c.url}`);
  return checks.every((c) => c.ok);
}

/**
 * Baseline data the catalogue's read-only cases expect to find: one imported
 * ISO 20022 schema. The upload suites remove what they create, so without
 * this a new staging database has no families, schemas or jobs to read.
 * Safe to repeat: a schema that is already stored is reported as a duplicate.
 */
async function seed() {
  const api = `http://127.0.0.1:${ports.api}`;
  const fileName = 'pacs.008.001.14.xsd';
  const content = readFileSync(path.join(root, 'data/iso20022-upload', fileName), 'utf8').replace(/^﻿/, '');
  const post = (url, body, headers = {}) =>
    fetch(url, { method: 'POST', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(body), signal: AbortSignal.timeout(60_000) });

  const login = await post(`${api}/api/v1/session/login`, { tenantSlug: 'acme-demo', username: 'operator.acme' });
  const { token } = await login.json().catch(() => ({}));
  if (!login.ok || !token) throw new Error(`baseline seed: demo sign-in returned HTTP ${login.status}`);
  const auth = { authorization: `Bearer ${token}` };

  const upload = await post(`${api}/api/v1/catalog/iso/uploads`, { xsdFileName: fileName, xsdContent: content, confirm: true, proceed: 'xsd-only' }, auth);
  if (upload.status !== 202 && upload.status !== 409) throw new Error(`baseline seed: ISO upload returned HTTP ${upload.status}: ${(await upload.text()).slice(0, 300)}`);
  console.log(`[staging] baseline ISO catalogue: ${fileName} ${upload.status === 202 ? 'imported' : 'already present'}`);

  const listed = await fetch(`${api}/api/v1/schemas`, { headers: auth, signal: AbortSignal.timeout(30_000) });
  const schemas = (await listed.json().catch(() => ({}))).data || [];
  if (schemas.length) {
    console.log(`[staging] baseline schema registry: ${schemas.length} schema(s) already present`);
    return;
  }
  const committed = await post(`${api}/api/v1/schemas`, { name: 'pacs.008.001.14 (staging baseline)', fileName, content }, auth);
  if (!committed.ok) throw new Error(`baseline seed: schema commit returned HTTP ${committed.status}: ${(await committed.text()).slice(0, 300)}`);
  console.log(`[staging] baseline schema registry: ${fileName} committed`);
}

/**
 * Targets are written for the host (127.0.0.1); a containerized worker
 * re-points them at the host gateway (apps/worker/src/worker.ts).
 */
/** What the engine shows as "deployed": the pinned commit, and whether the stack is up or down. */
function deploymentInfo(state) {
  if (!state) return { compose_project: PROJECT };
  return {
    compose_project: PROJECT, ref: state.ref, commit: state.commit, version: state.version, deployed_at: state.deployed_at,
    state: state.state || 'up',
    ...(state.torn_down_at ? { torn_down_at: state.torn_down_at } : {}),
  };
}

async function register(state) {
  const host = 'http://127.0.0.1';
  const existing = await fetch(`${engine}/api/v1/environments/${ENV_KEY}`);
  const existingConfig = existing.ok ? ((await existing.json().catch(() => ({}))).data || {}).config || {} : {};
  const body = {
    name: 'Sand Bench · local Docker (staging)',
    env_type: 'staging',
    base_url: `${host}:${ports.web}`,
    status: 'active',
    config: {
      applications: ['sand-bench'],
      vars: {
        web: `${host}:${ports.web}`,
        api: `${host}:${ports.api}`,
        testhub: `${host}:${ports.testhub}`,
        dbviewer: `${host}:${ports.dbviewer}`,
        engine,
        tenant: 'acme-demo',
        username: 'operator.acme',
        password: '',
      },
      secret_env: { password: 'SB_STAGING_PASSWORD' },
      // Managed by the engine's infrastructure lifecycle (apps/api/src/infra.ts): the infra agent
      // deploys and tears this stack down with this script. Hours set in the console are kept.
      infra: { ...(existingConfig.infra || {}), driver: 'compose', script: 'deploy/staging/deploy.mjs', compose_project: PROJECT },
      deployment: deploymentInfo(state),
    },
    safety_policy: {
      functional_smoke: 'allowed', read_only_api: 'allowed', write_api: 'allowed',
      load: 'allowed', soak: 'allowed', chaos: 'allowed', security_scan: 'allowed',
      stress: 'approval_required', destructive_db: 'prohibited',
    },
    updated_by: 'deploy/staging',
  };
  const json = { 'content-type': 'application/json' };
  const res = existing.ok
    ? await fetch(`${engine}/api/v1/environments/${ENV_KEY}`, { method: 'PATCH', headers: json, body: JSON.stringify(body) })
    : await fetch(`${engine}/api/v1/environments`, { method: 'POST', headers: json, body: JSON.stringify({ key: ENV_KEY, created_by: 'deploy/staging', ...body }) });
  if (!res.ok) throw new Error(`Test Engine refused the environment (${res.status}): ${(await res.text()).slice(0, 300)}`);
  console.log(`[staging] environment "${ENV_KEY}" ${existing.ok ? 'updated' : 'registered'} at ${engine}`);
}

function readState() {
  try {
    return JSON.parse(readFileSync(stateFile, 'utf8'));
  } catch {
    return null;
  }
}

async function main() {
  const args = process.argv.slice(2);
  const action = args[0] || 'help';

  if (action === 'deploy') {
    mkdirSync(path.join(home, 'src'), { recursive: true });
    ensureSecrets();
    const src = exportSource(option(args, 'ref', 'main'));
    console.log(`[staging] deploying ${src.tag} "${src.subject}"`);
    compose(src, ['build', ...SERVICES]);
    compose(src, ['up', '-d', '--wait', '--wait-timeout', '300', ...SERVICES]);
    const healthy = await verify();
    const state = { ref: src.ref, commit: src.commit, tag: src.tag, version: `${src.version}-staging`, subject: src.subject, source: src.dir, deployed_at: new Date().toISOString(), healthy };
    writeFileSync(stateFile, JSON.stringify(state, null, 2));
    pruneSources(src.tag);
    if (!healthy) throw new Error('staging is up but failed verification — not registering it');
    if (!args.includes('--no-seed')) await seed();
    if (!args.includes('--no-register')) await register(state);
    // Machine-readable summary for the infra agent (apps/infra-agent).
    console.log(`[staging] RESULT ${JSON.stringify({ ref: state.ref, commit: state.commit, version: state.version, deployed_at: state.deployed_at })}`);
    return;
  }

  const state = readState();
  if (action === 'register') return register(state);
  if (action === 'seed') return seed();

  // Take the stack down: containers and network always; images with --rmi, data volumes with --volumes.
  // Compose does the orderly part; the label sweep catches whatever it could not (sources pruned, a
  // shared image it refused to remove). The engine is told the stack is down.
  if (action === 'down') {
    const rmi = args.includes('--rmi');
    const volumes = args.includes('--volumes');
    if (state && existsSync(path.join(state.source, 'docker-compose.yml'))) {
      const src = { tag: state.tag, commit: state.commit, dir: state.source, version: state.version.replace(/-staging$/, '') };
      try {
        compose(src, ['down', '--remove-orphans', ...(rmi ? ['--rmi', 'all'] : []), ...(volumes ? ['-v'] : [])]);
      } catch (err) {
        console.warn(`[staging] compose down reported: ${err.message.split('\n')[0]} — sweeping by label`);
      }
    }
    sweep(rmi, volumes);
    if (state) {
      const next = { ...state, state: 'down', torn_down_at: new Date().toISOString(), healthy: false };
      writeFileSync(stateFile, JSON.stringify(next, null, 2));
      try {
        await register(next);
      } catch (err) {
        console.warn(`[staging] engine not updated: ${err.message}`);
      }
    }
    console.log(`[staging] ${PROJECT} is down${rmi ? ', images removed' : ''}${volumes ? ', volumes removed' : ''}`);
    return;
  }

  if (!state) throw new Error(`nothing deployed yet (no ${stateFile})`);
  const src = { tag: state.tag, commit: state.commit, dir: state.source, version: state.version.replace(/-staging$/, '') };

  if (action === 'status') {
    console.log(`[staging] ${state.tag} "${state.subject}" deployed ${state.deployed_at}`);
    console.log(compose(src, ['ps', '--format', 'table {{.Service}}\t{{.State}}\t{{.Health}}\t{{.Ports}}'], { inherit: false }));
    if (!(await verify())) process.exitCode = 1;
    return;
  }
  if (action === 'stop') return void compose(src, ['stop']);

  console.log('node deploy/staging/deploy.mjs <deploy [--ref REF] [--no-seed] [--no-register] | status | seed | register | stop | down [--rmi] [--volumes]>');
}

/** Remove everything still carrying this compose project's label. Each removal is best effort: an image another project shares stays. */
function sweep(rmi, volumes) {
  const filter = `label=com.docker.compose.project=${PROJECT}`;
  const ids = (out) => out.split(/\s+/).filter(Boolean);
  const containers = ids(run('docker', ['ps', '-aq', '--filter', filter]));
  if (containers.length) run('docker', ['rm', '-f', ...containers]);
  for (const id of ids(run('docker', ['network', 'ls', '-q', '--filter', filter]))) {
    try { run('docker', ['network', 'rm', id]); } catch { /* in use elsewhere */ }
  }
  let images = 0;
  if (rmi) {
    for (const id of new Set(ids(run('docker', ['images', '-q', '--filter', filter])))) {
      try { run('docker', ['rmi', id]); images++; } catch { /* another container uses it */ }
    }
  }
  if (volumes) {
    for (const name of ids(run('docker', ['volume', 'ls', '-q', '--filter', filter]))) {
      try { run('docker', ['volume', 'rm', name]); } catch { /* in use */ }
    }
  }
  console.log(`[staging] swept ${containers.length} container(s)${rmi ? `, ${images} image(s)` : ''} of ${PROJECT}`);
}

main().catch((err) => {
  console.error(`[staging] ${err.message}`);
  process.exit(1);
});
